#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'checkMagazine' function below.
#
# The function accepts following parameters:
#  1. STRING_ARRAY magazine
#  2. STRING_ARRAY note
#

def checkMagazine(magazine, note):
    d = {}
    #"give me one grand today night"
    #"give one grand today"
    for word in magazine:
        d.setdefault(word, 0)
        d[word] += 1
        
    subset = "Yes"
    for word in note:
        if word in d:
            d[word] -= 1
            if d[word] < 0:
                subset = "No"
                break
        else:
            subset = "No"
            break
                
    print (subset)
         
        
if __name__ == '__main__':
    first_multiple_input = input().rstrip().split()

    m = int(first_multiple_input[0])

    n = int(first_multiple_input[1])

    magazine = input().rstrip().split()

    note = input().rstrip().split()

    checkMagazine(magazine, note)
